[WB-792] Абстрактные файлы для работы с ClickHouse
EggheadsSolutions/cakephp-clickhouse pull request #2
Opened 2022-01-26 14:48 UTC by vendelev

2022-01-31 11:01 UTC, denyWhite approved these changes

2022-01-31 11:11 UTC, H-Kate requested changes

2022-01-31 11:11 UTC, H-Kate commented on src/ClickHouse.php
> +        return Configure::read('debug', false);
Не исправлять, а скорее на подумать. Если по каким-либо причинам не указать debug = true, то автоматом считается прод. Было бы лучше определять прод намеренным объявлением.

2022-01-31 11:11 UTC, H-Kate commented on src/ClickHouse.php
> +     * Включен ли режим отладки
ё

2022-01-31 11:11 UTC, H-Kate commented on src/ClickHouseTransaction.php
> +    private const WORK_DIR = 'clickHouse';
комментарий

2022-01-31 11:11 UTC, H-Kate commented on src/ClickHouseTransaction.php
> +    private string $_tableName;
комментарий

2022-01-31 11:11 UTC, H-Kate commented on src/ClickHouseTransaction.php
> +    private array $_schemaFields;
комментарий

2022-01-31 11:11 UTC, H-Kate commented on src/ClickHouseTransaction.php
> +    private array $_saveFields = [];
комментарий

2022-01-31 11:11 UTC, H-Kate commented on src/ClickHouseTransaction.php
> +    private $_stream;
комментарий, тип

2022-01-31 11:11 UTC, H-Kate commented on src/ClickHouseTransaction.php
> +    private string $_filePath;
комментарий

2022-01-31 11:11 UTC, H-Kate commented on src/ClickHouseTransaction.php
> +    private ClickHouse $_clickHouse;
комментарий

2022-01-31 11:11 UTC, H-Kate commented on tests/AbstractClickHouseTableTest/TestClickHouseTable.php
> +    public const TABLE = 'testTable';
комментарий

2022-01-31 11:11 UTC, H-Kate commented on tests/AbstractClickHouseTableTest/TestClickHouseTable.php
> +    public const WRITER_CONFIG = 'ssdNode';
комментарий

2022-01-31 11:11 UTC, H-Kate commented on tests/AbstractClickHouseTableTest/TestClickHouseTableTest.php
> +            "id" => "String",
Заменить " на '

2022-01-31 11:11 UTC, H-Kate commented on tests/AbstractClickHouseTableTest/TestClickHouseTableTest.php
> +            "id" => "String",
Посмотри по всему файлу

2022-01-31 11:16 UTC, vendelev commented on docker-compose.yml
> +#        ports:
Нужны, чтобы разраб, если потребуется не думал на каком порту работает CH.
Специально оставил

2022-01-31 11:37 UTC, vendelev commented on src/AbstractClickHouseTable.php
> +}
Все настроено как обычно, ошибок нет

2022-02-01 06:31 UTC, podchenko approved these changes

2022-02-01 07:34 UTC, H-Kate requested changes

2022-02-01 07:34 UTC, H-Kate commented on src/AbstractClickHouseTable.php
> +            throw new LogicException("Не задана константа TABLE для класса " . static::class);
Заменить " на '

2022-02-01 07:34 UTC, H-Kate commented on src/AbstractClickHouseTable.php
> +            throw new LogicException("Не задана константа WRITER_CONFIG для класса " . static::class);
Заменить " на '

2022-02-01 07:34 UTC, H-Kate commented on src/AbstractClickHouseTable.php
> +                throw new OutOfBoundsException('Поле $defaultField не найдено в таблице ' . static::TABLE);
Заменить ' на ", иначе текстом $defaultField будет.

2022-02-01 07:34 UTC, H-Kate commented on src/ClickHouse.php
> +     * Проброс select, дабы кол-во уменьшить вложенности
...дабы уменьшить кол-во вложенности

2022-02-01 07:34 UTC, H-Kate commented on src/ClickHouseTransaction.php
> +    private $_stream;
Тип

2022-02-01 07:42 UTC, vovantune approved these changes

2022-02-01 07:42 UTC, vovantune commented on src/ClickHouseTransaction.php
> +    private $_stream;
открыТый

2022-02-01 07:46 UTC, vovantune commented
добавь в README.md доку как подключить CH к проекту + нужен пример перманент мока для проекта, который можно скопировать будет

2022-02-01 09:16 UTC, H-Kate approved these changes

2022-02-01 09:17 UTC, merged